package configuracao

fun main() {

    val jdbcTemplate = Conexao().getJdbcTemplate()

/*
método execute() -> executa qualquer tipo de instrução SQL
OBS: O ";" ao final da instrução é opcional, porém, se houverem
     mais de 1 instrução SQL, deve ter o ";" ao final de cada uma
 */
    jdbcTemplate.execute("""
        create table IF NOT EXISTS carro (
            idCarro int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            modelo varchar(20) not null,
            ano int not null,
            potencia decimal(2,1) not null
        );
    """)

}